#!/usr/bin/env python3
"""
render-compose.py — generate a Docker Compose file for a ZooKeeper-based
Apache Kafka 3.9.2 cluster (ZooKeeper 3.9.5).

The generated file is the single source of truth for cluster topology:
unique broker ids, hostnames, data volumes, advertised listeners, host port
mappings and per-broker certificate mounts are all assigned deterministically.

Usage:
    ./scripts/render-compose.py --brokers 3 --zookeepers 3 > docker-compose.generated.yml
    ./scripts/render-compose.py --brokers 5 --zookeepers 3 --security-mode ssl > docker-compose.generated.yml

Defaults are read from the environment / .env (BROKER_COUNT, ZOOKEEPER_COUNT,
KAFKA_SECURITY_MODE, INTER_BROKER_LISTENER_NAME) when flags are omitted.

Validation rules:
    * ZooKeeper count must be 3 or 5 (odd quorum).
    * Kafka broker count must be >= 3.
    * security-mode must be plaintext | ssl | dual.
"""
import argparse
import os
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

PLAINTEXT_PORT = 9092
SSL_PORT = 9093
ZK_CLIENT_PORT = 2181
ZK_PEER_PORT = 2888
ZK_ELECTION_PORT = 3888

VALID_ZK = {3, 5}
VALID_MODES = {"plaintext", "ssl", "dual"}


def load_dotenv(path: Path) -> dict:
    """Minimal .env reader (KEY=VALUE, ignores comments/blank lines)."""
    values = {}
    if not path.is_file():
        return values
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, val = line.partition("=")
        values[key.strip()] = val.strip()
    return values


def env_default(dotenv: dict, key: str, fallback: str) -> str:
    return os.environ.get(key) or dotenv.get(key) or fallback


def die(msg: str) -> None:
    sys.stderr.write(f"render-compose: error: {msg}\n")
    sys.exit(2)


def host_ports(index: int):
    """Return (plaintext_host_port, ssl_host_port) or (None, None) if the
    broker index is too large to expose deterministically on the host."""
    if index > 9:
        return None, None
    return int(f"{index}{PLAINTEXT_PORT}"), int(f"{index}{SSL_PORT}")


def zoo_servers(zk_count: int) -> str:
    """'|'-separated ensemble definition consumed by the ZooKeeper entrypoint."""
    return "|".join(
        f"server.{i}=zookeeper{i}:{ZK_PEER_PORT}:{ZK_ELECTION_PORT};{ZK_CLIENT_PORT}"
        for i in range(1, zk_count + 1)
    )


def zk_connect(zk_count: int) -> str:
    return ",".join(f"zookeeper{i}:{ZK_CLIENT_PORT}" for i in range(1, zk_count + 1))


def render(brokers: int, zks: int, mode: str, inter_broker: str, dotenv: dict) -> str:
    need_ssl = mode in ("ssl", "dual")
    out = []
    w = out.append

    w("# ---------------------------------------------------------------------------")
    w("# GENERATED by scripts/render-compose.py — DO NOT EDIT BY HAND.")
    w(f"# brokers={brokers}  zookeepers={zks}  security_mode={mode}")
    w("# Re-render with: make render BROKERS=<n> ZOOKEEPERS=<n>")
    w("# ---------------------------------------------------------------------------")
    w("name: kafka-zookeeper-lab")
    w("")
    w("networks:")
    w("  kafka-net:")
    w("    name: kafka-net")
    w("    driver: bridge")
    w("")

    # ---- volumes ----
    w("volumes:")
    for i in range(1, zks + 1):
        w(f"  zookeeper{i}-data:")
        w(f"  zookeeper{i}-log:")
    for i in range(1, brokers + 1):
        w(f"  kafka{i}-data:")
    w("")

    w("services:")

    servers = zoo_servers(zks)

    # ---- ZooKeeper services ----
    for i in range(1, zks + 1):
        w(f"  zookeeper{i}:")
        w(f"    container_name: zookeeper{i}")
        w("    build:")
        w("      context: .")
        w("      dockerfile: images/zookeeper/Dockerfile")
        w("      args:")
        w("        ZOOKEEPER_VERSION: ${ZOOKEEPER_VERSION:-3.9.5}")
        w(f"    hostname: zookeeper{i}")
        w("    networks: [kafka-net]")
        w("    restart: unless-stopped")
        w("    environment:")
        w(f"      ZOO_MY_ID: \"{i}\"")
        w(f"      ZOO_SERVERS: \"{servers}\"")
        w(f"      ZOO_CLIENT_PORT: \"{ZK_CLIENT_PORT}\"")
        w("      ZOO_TICK_TIME: \"2000\"")
        w("      ZOO_INIT_LIMIT: \"10\"")
        w("      ZOO_SYNC_LIMIT: \"5\"")
        w("      ZOO_MAX_CLIENT_CNXNS: \"60\"")
        w("      ZOOKEEPER_HEAP_OPTS: ${ZOOKEEPER_HEAP_OPTS:--Xms256m -Xmx512m}")
        w("    volumes:")
        w(f"      - zookeeper{i}-data:/var/lib/zookeeper/data")
        w(f"      - zookeeper{i}-log:/var/lib/zookeeper/log")
        w("    healthcheck:")
        w("      test: [\"CMD-SHELL\", \"echo ruok | nc -w 2 localhost 2181 | grep -q imok\"]")
        w("      interval: 10s")
        w("      timeout: 5s")
        w("      retries: 12")
        w("      start_period: 20s")
        w("")

    zkc = zk_connect(zks)

    # ---- Kafka broker services ----
    for i in range(1, brokers + 1):
        p_host, s_host = host_ports(i)
        w(f"  kafka{i}:")
        w(f"    container_name: kafka{i}")
        w("    build:")
        w("      context: .")
        w("      dockerfile: images/kafka/Dockerfile")
        w("      args:")
        w("        KAFKA_VERSION: ${KAFKA_VERSION:-3.9.2}")
        w("        SCALA_VERSION: ${SCALA_VERSION:-2.13}")
        w(f"    hostname: kafka{i}")
        w("    networks: [kafka-net]")
        w("    restart: unless-stopped")
        w("    depends_on:")
        for z in range(1, zks + 1):
            w(f"      zookeeper{z}:")
            w("        condition: service_healthy")
        w("    environment:")
        w(f"      BROKER_ID: \"{i}\"")
        w(f"      BROKER_HOSTNAME: \"kafka{i}\"")
        w(f"      KAFKA_ZOOKEEPER_CONNECT: \"{zkc}\"")
        w(f"      KAFKA_SECURITY_MODE: \"{mode}\"")
        w(f"      INTER_BROKER_LISTENER_NAME: \"{inter_broker}\"")
        w("      KAFKA_HEAP_OPTS: ${KAFKA_HEAP_OPTS:--Xms512m -Xmx1g}")
        w("      NUM_PARTITIONS: ${NUM_PARTITIONS:-6}")
        w("      DEFAULT_REPLICATION_FACTOR: ${DEFAULT_REPLICATION_FACTOR:-3}")
        w("      MIN_INSYNC_REPLICAS: ${MIN_INSYNC_REPLICAS:-2}")
        w("      OFFSETS_TOPIC_REPLICATION_FACTOR: ${OFFSETS_TOPIC_REPLICATION_FACTOR:-3}")
        w("      TRANSACTION_STATE_LOG_REPLICATION_FACTOR: ${TRANSACTION_STATE_LOG_REPLICATION_FACTOR:-3}")
        w("      TRANSACTION_STATE_LOG_MIN_ISR: ${TRANSACTION_STATE_LOG_MIN_ISR:-2}")
        w("      LOG_RETENTION_HOURS: ${LOG_RETENTION_HOURS:-168}")
        w("      AUTO_CREATE_TOPICS_ENABLE: ${AUTO_CREATE_TOPICS_ENABLE:-false}")
        w("      DELETE_TOPIC_ENABLE: ${DELETE_TOPIC_ENABLE:-true}")
        if need_ssl:
            w("      KAFKA_SSL_PASSWORD: ${KAFKA_SSL_PASSWORD:-changeit}")
            w("      SSL_CLIENT_AUTH: ${SSL_CLIENT_AUTH:-none}")
            w("      SSL_ENABLED_PROTOCOLS: ${SSL_ENABLED_PROTOCOLS:-TLSv1.2,TLSv1.3}")
        # ports
        port_lines = []
        if mode in ("plaintext", "dual") and p_host:
            port_lines.append(f"      - \"{p_host}:{PLAINTEXT_PORT}\"")
        if mode in ("ssl", "dual") and s_host:
            port_lines.append(f"      - \"{s_host}:{SSL_PORT}\"")
        if port_lines:
            w("    ports:")
            for pl in port_lines:
                w(pl)
        elif i > 9:
            w(f"    # broker index {i} > 9: no host port mapping (reachable in-network only)")
        # volumes
        w("    volumes:")
        w(f"      - kafka{i}-data:/var/lib/kafka/data")
        if need_ssl:
            w(f"      - ./certs/generated/kafka{i}:/etc/kafka/secrets:ro")
        # healthcheck
        if mode == "ssl":
            w("    healthcheck:")
            w("      test: [\"CMD-SHELL\", \"kafka-broker-api-versions.sh --bootstrap-server localhost:9093 --command-config /opt/kafka/config/client-ssl.properties >/dev/null 2>&1\"]")
        else:
            w("    healthcheck:")
            w("      test: [\"CMD-SHELL\", \"kafka-broker-api-versions.sh --bootstrap-server localhost:9092 >/dev/null 2>&1\"]")
        w("      interval: 15s")
        w("      timeout: 10s")
        w("      retries: 12")
        w("      start_period: 45s")
        w("")

    return "\n".join(out) + "\n"


def main() -> None:
    dotenv = load_dotenv(REPO_ROOT / ".env")

    parser = argparse.ArgumentParser(description="Render a Kafka+ZooKeeper Docker Compose file.")
    parser.add_argument("--brokers", type=int,
                        default=int(env_default(dotenv, "BROKER_COUNT", "3")),
                        help="number of Kafka brokers (>=3, default from BROKER_COUNT)")
    parser.add_argument("--zookeepers", type=int,
                        default=int(env_default(dotenv, "ZOOKEEPER_COUNT", "3")),
                        help="number of ZooKeeper nodes (3 or 5, default from ZOOKEEPER_COUNT)")
    parser.add_argument("--security-mode",
                        default=env_default(dotenv, "KAFKA_SECURITY_MODE", "dual"),
                        choices=sorted(VALID_MODES),
                        help="plaintext | ssl | dual (default from KAFKA_SECURITY_MODE)")
    parser.add_argument("--inter-broker",
                        default=env_default(dotenv, "INTER_BROKER_LISTENER_NAME", "SSL"),
                        help="inter-broker listener name (default from INTER_BROKER_LISTENER_NAME)")
    parser.add_argument("-o", "--output", default="-",
                        help="output file (default '-' = stdout)")
    args = parser.parse_args()

    # ---- validation ----
    if args.zookeepers not in VALID_ZK:
        die(f"ZooKeeper count must be 3 or 5, got {args.zookeepers}")
    if args.brokers < 3:
        die(f"Kafka broker count must be >= 3, got {args.brokers}")
    if args.security_mode not in VALID_MODES:
        die(f"security-mode must be one of {sorted(VALID_MODES)}, got {args.security_mode}")

    inter = args.inter_broker
    if args.security_mode == "plaintext":
        inter = "PLAINTEXT"

    content = render(args.brokers, args.zookeepers, args.security_mode, inter, dotenv)

    if args.output == "-":
        sys.stdout.write(content)
    else:
        Path(args.output).write_text(content)
        sys.stderr.write(
            f"render-compose: wrote {args.output} "
            f"({args.brokers} brokers, {args.zookeepers} zookeepers, {args.security_mode})\n"
        )


if __name__ == "__main__":
    main()
